version: "3"

services:
  blaze_3000:
    image: dhf0820/uc_blaze:240127.0
    ports:
      - 80:3000
    deploy:
      replicas: 1   

    networks:
      - uc

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    command:
      - --storageEngine=wiredTiger
    networks:
      - uc

networks:
  uc:
   
 
 
    
